//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN.Module.ORMDataModel1
{

    public partial class Order_Detail : XPObject
    {
        Order fOrderId;
        [Association(@"Order_DetailReferencesOrder")]
        public Order OrderId
        {
            get { return fOrderId; }
            set { SetPropertyValue<Order>(nameof(OrderId), ref fOrderId, value); }
        }
        short fQuantity;
        public short Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<short>(nameof(Quantity), ref fQuantity, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
        Product_Detail fProductDetailId;
        [Association(@"Order_DetailReferencesProduct_Detail")]
        public Product_Detail ProductDetailId
        {
            get { return fProductDetailId; }
            set { SetPropertyValue<Product_Detail>(nameof(ProductDetailId), ref fProductDetailId, value); }
        }
    }

}
