//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN.Module.ORMDataModel1
{

    public partial class Order : XPObject
    {
        User fUserId;
        [Association(@"OrderReferencesUser")]
        public User UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<User>(nameof(UserId), ref fUserId, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        double fTotalPrice;
        public double TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<double>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        DateTime fCreateTime;
        public DateTime CreateTime
        {
            get { return fCreateTime; }
            set { SetPropertyValue<DateTime>(nameof(CreateTime), ref fCreateTime, value); }
        }
        DateTime fUpdateTime;
        public DateTime UpdateTime
        {
            get { return fUpdateTime; }
            set { SetPropertyValue<DateTime>(nameof(UpdateTime), ref fUpdateTime, value); }
        }
        [Association(@"Order_DetailReferencesOrder")]
        public XPCollection<Order_Detail> Order_Details { get { return GetCollection<Order_Detail>(nameof(Order_Details)); } }
    }

}
