//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN.Module.ORMDataModel1
{

    public partial class Product : XPObject
    {
        string fNameProduct;
        public string NameProduct
        {
            get { return fNameProduct; }
            set { SetPropertyValue<string>(nameof(NameProduct), ref fNameProduct, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fImages;
        public string Images
        {
            get { return fImages; }
            set { SetPropertyValue<string>(nameof(Images), ref fImages, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
        string fBrand;
        public string Brand
        {
            get { return fBrand; }
            set { SetPropertyValue<string>(nameof(Brand), ref fBrand, value); }
        }
        Category fCategoryId;
        [Association(@"ProductReferencesCategory")]
        public Category CategoryId
        {
            get { return fCategoryId; }
            set { SetPropertyValue<Category>(nameof(CategoryId), ref fCategoryId, value); }
        }
        [Association(@"Product_DetailReferencesProduct")]
        public XPCollection<Product_Detail> Product_Details { get { return GetCollection<Product_Detail>(nameof(Product_Details)); } }
    }

}
