//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN.Module.ORMDataModel1
{

    public partial class Store : XPObject
    {
        User fUserId;
        [Association(@"StoreReferencesUser")]
        public User UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<User>(nameof(UserId), ref fUserId, value); }
        }
        DateTime fDatetime;
        public DateTime Datetime
        {
            get { return fDatetime; }
            set { SetPropertyValue<DateTime>(nameof(Datetime), ref fDatetime, value); }
        }
        Provider fProviderId;
        [Association(@"StoreReferencesProvider")]
        public Provider ProviderId
        {
            get { return fProviderId; }
            set { SetPropertyValue<Provider>(nameof(ProviderId), ref fProviderId, value); }
        }
        [Association(@"Store_DetailReferencesStore")]
        public XPCollection<Store_Detail> Store_Details { get { return GetCollection<Store_Detail>(nameof(Store_Details)); } }
    }

}
