//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN.Module.ORMDataModel1
{

    public partial class Store_Detail : XPObject
    {
        Store fStoreId;
        [Association(@"Store_DetailReferencesStore")]
        public Store StoreId
        {
            get { return fStoreId; }
            set { SetPropertyValue<Store>(nameof(StoreId), ref fStoreId, value); }
        }
        Product_Detail fProductDetailId;
        [Association(@"Store_DetailReferencesProduct_Detail")]
        public Product_Detail ProductDetailId
        {
            get { return fProductDetailId; }
            set { SetPropertyValue<Product_Detail>(nameof(ProductDetailId), ref fProductDetailId, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
    }

}
